"""What a reader is shown: the machine's own working taken out.

The owner, 2026-09-11, looking at the published desk: no declarations about
packets, sources, vendors or how a figure was produced, anywhere a reader can
see, and scrubbed from what had already been uploaded. The morning report,
the midday report and the desk's inlined session data all carried that
working, because each was written first as a record and only later shown to
anybody.

SPLIT, NOT DELETE, the rule the Screens memo already applied to the catalyst
sentence. Every file on disk keeps every word: report.md, report_midday.md,
packet.json and each session's frozen desk.json.gz are the record, and the
suite's claims about them still read them whole. What passes through here is
the READER'S COPY: the report rendered for the desk and for the email, and the
session payload inlined into site/PremarketDesk.html, which is published and
which anyone can decode.

Three tools, one vocabulary:

  reader_markdown   a report with every sentence that names the machine
                    removed, the Source column dropped from its tables, the
                    old vendor tagged catalyst sentence rewritten, and any
                    heading left with nothing under it dropped.
  desk_payload      a session payload with the keys no screen reads removed
                    and the prose fields a screen does read put through the
                    same sentence filter.
  machine_words     the vocabulary itself, one pattern, so the report, the
                    payload and the claim that guards them cannot disagree
                    about what counts.

A SENTENCE IS THE UNIT. Dropping a whole paragraph for one machine word lost
the market summary, whose one sentence about the tape ended "on the
collector". So the benign mentions are rewritten first, a sentence that still
names the machine is dropped, and the rest of its paragraph stands.
"""

from __future__ import annotations

import copy
import re
from typing import Any

from core import glossary

# ---------------------------------------------------------------- vocabulary

# What marks a sentence as the machine talking about itself. Deliberately
# phrases rather than bare words wherever a bare word is also English a
# market uses: POOL is a ticker, credit is a market, a sweep is also a broom.
_MACHINE = re.compile(
    r"\bpackets?\b|\bcollector'?s?\b|\bsockets?\b|\bvendor'?s?\b|\bEODHD\b"
    r"|\bAlpaca\b|\bCRITERIA(?:\.md)?\b"
    # a CRITERIA section cited in brackets, [Price age], and not a link
    r"|\[[A-Z][a-z]+(?: [a-z]+)?\](?!\()"
    r"|\bcached?\b|\bpayloads?\b|\bfixtures?\b"
    r"|\b(?:the|into the|provisional|replayed) pool\b|\bpool (?:rewrite|tier|had)\b"
    r"|\bDiscover\b|\bsubscri(?:bed|ption|ptions|be)\b"
    r"|\bdenominators?\b|\bnumerators?\b"
    r"|\bcapture (?:share|correction|basis)\b|\btruth pass\b|\bthe nightly\b"
    r"|\bnightly check\b|\bquantifier\b|\bevidence gaps?\b"
    r"|\bten credits\b|\bcredits each\b|\bfundamentals calls?\b|\bendpoints?\b"
    r"|\bbulk (?:close|call|payload)\b|\bthe feed\b|\bthe news feed\b"
    r"|\b[\w-]+\.(?:py|jsonl?|md|gz|db|csv)\b"
    # a snake case field name, premarket_rvol, catalyst_found
    r"|\b[a-z]+_[a-z][a-z_]*\b"
    r"|\bcalls? left\b|\bpreflight\b|\bvendor calls?\b"
    r"|\bGenerated \d{4}-\d\d-\d\dT|\bgenerated by PremarketDesk\b"
    r"|\bthe scan (?:recorded|clock)\b|\bscan clock\b"
    r"|\bon file\b|\bon disk\b|\breplay(?:ed|s|ing)?\b|\breconstruct(?:ed|ion)?\b"
    r"|\buniverse symbols\b"
    r"|\bthe model\b|\bread_quote\b|\buniverse names quoted\b|\bthe night measures\b"
    r"|\bthe roll'?s?\b",
    re.IGNORECASE)


def machine_words(text: str) -> list[str]:
    """Every machine phrase in text, as found. Empty for a reader's sentence."""
    return [m.group(0) for m in _MACHINE.finditer(text or "")]


# Benign mentions, rewritten before a sentence is judged, so a sentence whose
# only fault is a trailing "on the collector" keeps its market content.
_REWRITES: tuple[tuple[re.Pattern[str], Any], ...] = (
    (re.compile(r"\s+on the collector\b"), ""),
    (re.compile(r"\bin the packet window\b"), "in the window"),
    (re.compile(r"\bpacket window\b"), "window"),
    (re.compile(r";\s*Source is where this figure came from"), ""),
    (re.compile(r"this system replays one written rule over the record after "
                r"the fact, and that rule"),
     "one written rule is applied to the record after the fact, and it"),
    (re.compile(r"\bthe last collector print is ([\d,]+)s old at the scan clock, "
                r"past \[Price age\] max_price_age_seconds"),
     lambda m: f"its most recent price is {round(int(m.group(1).replace(',', '')) / 60)} "
               "minutes old, too stale to judge it on"),
    (re.compile(r"\bno cached baseline for this ticker and cutoff\b"),
     "there were no earlier mornings to compare it against"),
    # the thin trading warning, one line per name, which is a reader's fact
    # about the share said in the machine's voice
    (re.compile(r"\bthe collector saw ([\d,]+ share\(s\)) over"), r"only \1 traded over"),
    # the Similar screen's survivorship caveat, which a reader needs and which
    # named the replay; the fact is kept, the mechanism is not
    (re.compile(r"\bThe replayed universe is today's"), "The list of shares tested is today's"),
    # the midday table's reach column, the pool's own words for a reader's fact
    (re.compile(r"\bpooled not subscribed\b"), "found overnight, not watched"),
    (re.compile(r"\bnot pooled\b"), "not found overnight"),
    # a ranked list's line as sessions before 2026-09-03 wrote it, with the
    # list and leg keys raw, "the prior_session_by_sigma list ... on the
    # prior_session leg"; put in words as morning.scan has written them since
    (re.compile(r"\b(?:prior_session|two_session|premarket)(?:_by_[a-z_]+)?\b"),
     lambda m: glossary.in_words(m.group(0))),
    (re.compile(r"^(Trap undecided for [^:]+):.*$"),
     r"\1: the news could not settle it either way, and undecided is not a "
     r"verdict of safe."),
)

# The one report section that is mostly the machine's own diagnostics. Only
# the blocks a reader acts on are kept, each with the bullets under it; a
# sentence filter alone left orphans like "These ratios are published,
# screened on and scored like the rest" once their lead sentence had gone.
_DIAGNOSTIC_SECTION = "skips and traps"
_READER_LEADS = re.compile(
    r"^(?:Moving on no found catalyst|Premarket path partial|Traps:"
    r"|The trap question|Trap undecided for|\d+ of \d+ candidates traded so little)")

# The catalyst sentence as it was written before 2026-09-10, when it was one
# sentence for two audiences. Rewritten to the reader's half of what
# morning.scan.classify_catalyst writes now.
_OLD_CATALYST = re.compile(
    r"EODHD news tag (?:'[^']*'|\"[^\"]*\") mapped through CRITERIA\.md, from "
    r"(?P<title>'(?:[^'\\]|\\.)*'|\"(?:[^\"\\]|\\.)*\")"
    r"(?:, an article carrying \d+ tag\(s\) and returned for (?P<returned>\d+) "
    r"of this morning's (?P<checked>\d+) candidates)?"
    r"(?:\. Its tags: [^.]*)?")
# And the gapper block of the same era, which printed three field names.
_OLD_CLASS = re.compile(
    r"Catalyst class (?P<cls>[a-z_]+), catalyst_found (?:true|false)\. catalyst_why: ")


def _old_catalyst(match: re.Match[str]) -> str:
    title = match.group("title")[1:-1]
    text = f"from the story '{title}'."
    returned, checked = match.group("returned"), match.group("checked")
    if returned == "1" and checked:
        text += (f" Of the {checked} names looked at this morning, that story "
                 "came back for this one alone, so it is about this company.")
    elif returned and checked:
        text += (f" That story also came back for {returned} of the {checked} "
                 "names looked at this morning, so it may be about the market "
                 "rather than about this company.")
    return text


def plain(text: str) -> str:
    """The rewrites alone: old catalyst sentences and benign mentions."""
    out = _OLD_CLASS.sub(
        lambda m: f"Catalyst: {glossary.catalyst_class(m.group('cls'))}, ", text or "")
    out = _OLD_CATALYST.sub(_old_catalyst, out)
    for pattern, replacement in _REWRITES:
        out = pattern.sub(replacement, out)
    return out


# A sentence ends at . ! or ? followed by space and a capital, a digit or a
# quote. A false split costs at most half a sentence that named the machine;
# the rest is rejoined exactly, whitespace and all.
_SENTENCE_END = re.compile(r"(?<=[.!?])(\s+)(?=[A-Z0-9\"'(*])")


def sentences(text: str) -> str:
    """text with every sentence that still names the machine removed."""
    rewritten = plain(text)
    parts = _SENTENCE_END.split(rewritten)
    # split keeps the separators at odd indexes
    kept: list[str] = []
    for index in range(0, len(parts), 2):
        piece = parts[index]
        if machine_words(piece):
            continue
        if kept:
            kept.append(parts[index - 1] if index else " ")
        kept.append(piece)
    return "".join(kept).strip()


# ------------------------------------------------------------------ reports

_TABLE_ROW = re.compile(r"^\s*\|")
_HEADING = re.compile(r"^(#{1,6})\s")
# The opening disclaimer of a morning report, one paragraph that was mostly
# the machine describing its own evidence. Its first clause is the one a
# reader needs, and it is kept in words that name nothing.
_DISCLAIMER_OPENING = "Nothing here is advice, the screen thresholds are unvalidated"
DISCLAIMER = ("Nothing here is advice, and the screen thresholds are starting "
              "values that have not been shown to work.")


def _cells(line: str) -> list[str]:
    body = line.strip()
    if body.startswith("|"):
        body = body[1:]
    if body.endswith("|"):
        body = body[:-1]
    return [cell.strip() for cell in body.split("|")]


def _table(lines: list[str]) -> list[str]:
    """A markdown table without its Source column and without machine rows."""
    if len(lines) < 2:
        return lines
    header = _cells(lines[0])
    drop = {i for i, name in enumerate(header) if name.lower() == "source"}
    out: list[str] = []
    for position, line in enumerate(lines):
        cells = [cell for i, cell in enumerate(_cells(line)) if i not in drop]
        if position >= 2 and machine_words(" ".join(cells)):
            continue
        out.append("| " + " | ".join(cells) + " |")
    return out if len(out) > 2 else []


def _line(line: str) -> str | None:
    """One markdown line for a reader, or None when nothing of it is left."""
    if line.startswith(_DISCLAIMER_OPENING):
        return DISCLAIMER
    stripped = line.lstrip()
    for marker in ("- ", "* "):
        if stripped.startswith(marker):
            indent = line[: len(line) - len(stripped)]
            kept = sentences(stripped[len(marker):])
            return f"{indent}{marker}{kept}" if kept else None
    kept = sentences(line)
    return kept or None


def reader_markdown(markdown: str) -> str:
    """A report with the machine's working taken out. See the module docstring."""
    lines = markdown.splitlines()
    out: list[str] = []
    index = 0
    section = ""
    keeping_block = True
    while index < len(lines):
        line = lines[index]
        heading = _HEADING.match(line)
        if heading and len(heading.group(1)) == 2:
            section = line[3:].strip().lower()
        if section == _DIAGNOSTIC_SECTION and not heading and line.strip():
            bullet = line.lstrip().startswith(("- ", "* "))
            if not bullet:
                keeping_block = bool(_READER_LEADS.match(line.strip()))
            index += 1
            if keeping_block:
                kept = _line(line)
                if kept is not None:
                    out.append(kept)
            continue
        if _TABLE_ROW.match(line):
            block = []
            while index < len(lines) and _TABLE_ROW.match(lines[index]):
                block.append(lines[index])
                index += 1
            out.extend(_table(block))
            continue
        index += 1
        if not line.strip() or _HEADING.match(line):
            out.append(line)
            continue
        kept = _line(line)
        if kept is not None:
            out.append(kept)
    return _drop_empty_sections(out)


def _drop_empty_sections(lines: list[str]) -> str:
    """Remove a heading whose section ended up with no text under it."""
    keep = [True] * len(lines)
    for index, line in enumerate(lines):
        heading = _HEADING.match(line)
        if not heading:
            continue
        level = len(heading.group(1))
        body = False
        for later in lines[index + 1:]:
            deeper = _HEADING.match(later)
            if deeper and len(deeper.group(1)) <= level:
                break
            if later.strip() and not deeper:
                body = True
                break
        keep[index] = body
    text = "\n".join(line for line, ok in zip(lines, keep) if ok)
    return re.sub(r"\n{3,}", "\n\n", text).strip() + "\n"


# ------------------------------------------------------- the failure lines

def _big(value: float) -> str:
    for size, suffix in ((1e12, "T"), (1e9, "B"), (1e6, "M"), (1e3, "K")):
        if abs(value) >= size:
            return f"{value / size:.1f}{suffix}"
    return f"{value:.0f}"


# The shapes a screen's refusal line takes, in the words desk/assets.py's
# plainFail already draws them in. Ported so the published data says what
# the screen says: a decoded payload that read "market_cap 871847340.0 fails
# > 1B" beside a card reading "worth about 871.8M" was two documents.
_FAILS: tuple[tuple[re.Pattern[str], Any], ...] = (
    (re.compile(r"^gap_pct ([\d.]+) fails >=? ([\d.]+)"),
     lambda m: f"it moved {m.group(1)} percent overnight, and this list asks "
               f"for {m.group(2)} percent or more"),
    (re.compile(r"^market_cap ([\d.]+) fails >=? ?(\S+)"),
     lambda m: f"the whole company is worth about {_big(float(m.group(1)))}, and "
               f"this list asks for more than {m.group(2)}"),
    (re.compile(r"^premarket_rvol was never measured: baseline median volume "
                r"([\d,.]+) shares? is below.*$"),
     lambda m: "how busy its trading was this morning could not be judged: on an "
               f"ordinary morning only about {m.group(1)} of its shares change "
               "hands before the open, which is too few to measure this morning "
               "against"),
    (re.compile(r"^premarket_rvol was never measured: .*$"),
     lambda m: "how busy its trading was against its own normal could not be "
               "worked out, because there were no earlier mornings to compare "
               "it against"),
    (re.compile(r"^premarket_rvol ([\d.]+) fails >=? ([\d.]+)"),
     lambda m: f"its trading before the open was {m.group(1)} times its own "
               f"normal, and this list asks for {m.group(2)} times"),
)


def fail_words(line: str) -> str:
    """One refusal line in the reader's words; an unknown shape through plain()."""
    for pattern, replacement in _FAILS:
        if pattern.match(line or ""):
            return pattern.sub(replacement, line)
    return plain(line)


_RANKS_ON = {"a move_sigma": "how unusual the move was for that share",
             "a market cap on file": "company size"}


# ------------------------------------------------------------ desk payloads

# Keys no screen reads, each of them the machine's working. Dropped from the
# published copy rather than filtered, because there is no reader's half.
_DROP_TOP = ("health", "vintage", "api_calls", "generated", "bars_source")
_DROP_PROV = ("membership", "selection_method")
_DROP_RANKING = ("cap_source", "ranked_on")


def _walk_prose(value: Any) -> Any:
    """Every string inside value through the sentence filter."""
    if isinstance(value, str):
        return sentences(value) if (" " in value and len(value) > 20) else value
    if isinstance(value, list):
        return [_walk_prose(item) for item in value]
    if isinstance(value, dict):
        return {key: _walk_prose(item) for key, item in value.items()}
    return value


def desk_payload(payload: dict[str, Any], keep: tuple[str, ...] = ()) -> dict[str, Any]:
    """A session payload as it may be published. The input is not modified.

    Only the prose fields are filtered. A headline, a company name and a
    ticker are the market's words and pass untouched, whatever they say.

    keep names top level keys to leave in, for the desk built for this
    machine only: its Health screen reads health and bars_source, and that
    copy is never uploaded. Everything else is filtered the same, so the two
    desks differ by that one screen and nothing a reader would notice.
    """
    out = copy.deepcopy(payload)
    for key in _DROP_TOP:
        if key not in keep:
            out.pop(key, None)
    # A session no scheduled morning produced carries the machine's reason,
    # "its packet was built by 'stub', which is not a commit". The screen
    # needs the fact and not the reason; found by the suite, whose own
    # entrypoint claims leave exactly such a session in the sandbox.
    if out.get("fixture"):
        out["fixture"] = "This session came from a test run, not from a scheduled morning"
    prov = out.get("prov")
    if isinstance(prov, dict):
        for key in _DROP_PROV:
            prov.pop(key, None)
        ranking = prov.get("ranking")
        if isinstance(ranking, dict):
            for key in _DROP_RANKING:
                ranking.pop(key, None)
    for board in ("day", "swing"):
        tally = (out.get("tally") or {}).get(board)
        if isinstance(tally, dict):
            tally.pop("failed_summary", None)

    # The catalyst class is a snake case key the screens print as a label, and
    # the desk only ever compares it with "none", which reads the same in
    # words. So it is published in words: analyst_action as analyst action.
    shape = out.get("shape")
    if isinstance(shape, dict) and isinstance(shape.get("catalyst_classes"), dict):
        shape["catalyst_classes"] = {glossary.catalyst_class(key): value for key, value
                                     in shape["catalyst_classes"].items()}
    for candidate in out.get("candidates") or []:
        if isinstance(candidate.get("catalyst"), str):
            candidate["catalyst"] = glossary.catalyst_class(candidate["catalyst"])
        for key in ("catalyst_why", "trap_why", "why"):
            if isinstance(candidate.get(key), str):
                candidate[key] = sentences(candidate[key])
        for key in ("day_failed", "swing_failed"):
            if isinstance(candidate.get(key), list):
                candidate[key] = [fail_words(item) for item in candidate[key]]
        for component in candidate.get("components") or []:
            if isinstance(component.get("why"), str):
                component["why"] = sentences(component["why"])
        if isinstance(candidate.get("pol"), dict):
            candidate["pol"].pop("source", None)
        if isinstance(candidate.get("mid"), dict) and isinstance(candidate["mid"].get("why"), str):
            candidate["mid"]["why"] = sentences(candidate["mid"]["why"])

    midday = out.get("midday")
    if isinstance(midday, dict):
        tally = midday.get("tally")
        if isinstance(tally, dict):
            tally.pop("refused_note", None)
            tally.pop("unpriced_note", None)
    # Each list's one line, "5 selected of 35 qualified of 35 considered on
    # the premarket leg", is the reader's fact and the owner asked for it back
    # the same day. Its counts stay; a reason appended after them goes through
    # the sentence filter like any other prose.
    for listing in (out.get("mover_lists") or {}).values():
        if isinstance(listing, dict):
            if isinstance(listing.get("text"), str):
                listing["text"] = sentences(listing["text"])
            ranks_on = listing.get("ranks_on")
            if isinstance(ranks_on, str):
                listing["ranks_on"] = _RANKS_ON.get(ranks_on, glossary.in_words(ranks_on))
    precedent = out.get("precedent")
    if isinstance(precedent, dict):
        for block in precedent.values():
            if isinstance(block, dict):
                block.pop("command", None)
        out["precedent"] = _walk_prose(precedent)
    return out
